# Generated by Django 5.2.1 on 2025-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=8, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
