# Generated by Django 5.2.1 on 2025-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PHONE', 'Телефон'), ('EMAIL', 'Email'), ('ADDRESS', 'Адрес'), ('SOCIAL', 'Соцсеть')], max_length=10, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('MSK', 'Москва'), ('SPB', 'Санкт-Петербург'), ('EKB', 'Екатеринбург'), ('KZN', 'Казань'), ('NNV', 'Нижний Новгород')], max_length=3, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('opening_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главный магазин')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['-is_main', 'city'],
            },
        ),
    ]
