# Generated by Django 5.2.1 on 2025-06-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_country_manufacturer_products_views_products_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страну', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производителя', 'verbose_name_plural': 'Производители'},
        ),
    ]
