# Generated by Django 5.2.1 on 2025-06-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_country_options_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.subcategories', verbose_name='Подкатегория'),
        ),
    ]
