# Generated by Django 5.2.1 on 2025-06-10 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0007_alter_country_options_alter_manufacturer_options'),
        ('main', '0002_contact_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='ID пользователя Telegram')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя')),
                ('feedback_type', models.CharField(choices=[('shop', 'О магазине'), ('product', 'О товаре')], max_length=10, verbose_name='Тип отзыва')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Обработан')),
                ('forwarded_to_operator', models.BooleanField(default=False, verbose_name='Передано оператору')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.products', verbose_name='Товар')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
