# Generated by Django 5.2.1 on 2025-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя Telegram')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='Ответ оператора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Запрос оператору',
                'verbose_name_plural': 'Запросы оператору',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администратора'),
        ),
    ]
